apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: attest-webhook-secret
  namespace: platform
spec:
  encryptedData:
    token: REPLACE_ME
  template:
    metadata:
      name: attest-webhook-secret
      namespace: platform
