---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: attest-webhook-secret
  namespace: platform
spec:
  encryptedData:
    token: AgBalWCTxBoUwjC0DcOsKwnPq/JJryOnJbL67mFSbwOGSF8GvEO4BfwZHphARR64+VGVAot1PXVbykgNWG0/se9kT5eCBrKIC022TJ+FG6Xv3kitAILUI9MSWNSvpJLlYWTe+J4RAho4G/LFDYewQApc35L5osPtH4kiFN6WLr5xSzwluUOuM0Y5IojyIo7QnlA3FUiFt0y309IH8vT9CnyrEM5PKx6nO17RDncYtfFuS7MANipg/UK5rI0QIPwCrNvbaKqlXGqT0kJkenrB4pMp0kWaR54J1m23stIEGkKiK/K3FMbdLR0ICjBVazzO18m1BZTQKxbaEHap5IUmAYP2gTlggwB6kOk8QMwKg9Lx8Vu9dln089UD3fX7OADDihpTWiitfUbGxmUt/Itnjz4clFIA9eg/zj7GrLWpH3Rr2GFjKDajS7zXJidr91Cib4Fy0VRcZGEhUwAUVCmzbyyTwcX+EqFsJxByYu9ZXDgWf9n521FSIV4tukds9D22qc7pwO7k1l5hWeNxgRTF79FIBI7LsIFQ1M99Dg+GfAj25XluZ+d5XfbRar6a/CsDXP8gtmvbE5XHMHDRbR213Ul8x91ndX/Iiv6hMzT0RaLM4ihNscL7/U3azsXE428uE4SLKBAoABiOfh33FwDyceFIoBfS37v0IfWuqc5lrULZTxig7ja1TswpRYxPMGj/NaGeTe+ezY46gL/7Nl6kJY5jMm8knjeih5HTnTFas17e8o+PAe96cXJgdxi8charqdhHfXJ77EmCf4RLhY6XM/gM
  template:
    metadata:
      name: attest-webhook-secret
      namespace: platform
