---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: attest-webhook-secret
  namespace: platform
spec:
  encryptedData:
    token: AgB4SDuK2j9tx4S0u45PvR07/IEoIyfjx5R3I7Bhr8T7ViOdBUoXqfya/QeO9JkQz0q5lgjWDZ5/9Qp/sq45qtFQQPAsEMv9BlW/J1ak5etgeVWxMH/VGfASMQlzpYXK73NgXrCioP5K8V0FmPLahx3gC6UbtG0WCuoN3F/vfUCoqTNAbLiQ+u1Iez3kMSGL4OdfbBsvMaR0dpSdzng8ZaT+UdlMItsZI7DouR22IbWPM1WKQWzGcttOLpezRKyi/p0UPNRNsFgwC950K4kghvzJLLDY3xr8gC18ybyz4csmCVzBAmDpjULUOdGJ/UvYSxWA9rAOeOpUcVffzOi6yEGurDAjWOGXHgiDL2eoyt/IFJ4WT4paUscfoENfLYrLrDkF7/V4FNf9etZHay4QRxHXSpdFJlJ2ZJ3vjGMDI4KD+jH1CAmHsXbM+JunAFk1LYvo7drueRycd8RwqHtRj0221BgDmV6y50adnoTBb4lZi4+ZlgjJo6FqrmMYqPDHBjr/5rtCBY6fsKfrB76NxqitRN4uJEYDkIi41mjKCY8RM4k04nczsNNsW5EDTIsoX7q8RZ3hu8eY1znq6FCRBbkSY6n+T/UiZYQeW6UkhDdg6Ljjr2C5b4zQ/gbKuMCd3kU+vj5eFnHHa6Ax+PpurIx04GRnb1LROwSselhy+VW3agcm1lz8cocMcLfUVkuYJVYzwCqCUOiTMLKYmyWeH82bNtD8y0LBDU2yQZNq74efzob8MnOwym5/
  template:
    metadata:
      creationTimestamp: null
      name: attest-webhook-secret
      namespace: platform
