---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: jenkins-operator-credentials-jenkins
  namespace: platform
spec:
  encryptedData:
    token: AgACK6gGkZ/lTVfT4MQoeM6uhLbc2zZFj2GfU5O3ulk6Gth2Bgmk0LQtAAj+XRuEzJWKKG6ty4+1fmeGLGdLR0lMqPmg852j+HKtMQfQRT0q1cix0zC9LkErkOKSysGY4mfBmvWk6HmSAd2Tjza4FDFbP+yc5ZXRBpI/098OyhHxBQg8eNtyVxRJfC8HC9nqNdNqiUMhluKk/+P59oRmetarDcVEUD8n6MW/0wAeVEh3XYTI3YBpJgHxqMoPLNem0ttAyW86KIswj1Z4+aTOIiNeS3iUyIzntnXWLQJdH6E8B0v0Vr6omgdKsToAl2+9u80CRYID7aVI6QcauronRUVOdukrm9difNFxiueLSIIpDHFNRW8v3jztussK0upgrvVnhNVJJ/k0ML1TQEeVBYzqbYH8PLtaIcLnN5mCHTg/x6NYm3Obmij9dCKHLb5G02NXazvN/EKeZ0TAyk/nHh1nsHXNNu72EK4NUmVatT8A5MGBwEvZ3ex5SbmqmQdKmUwMkUxM7mARmi2IePi4BCSQN1a5CXEBcYcizHO24ATMkKmljaVXUuToPGUWeMD8i9fAj5lYhHegrp7xo6E+m6MhRInZz0AUBEwyMN2nOt9gDfnSWvleMEDFnpxCskf/aYdXBOOBRm8EFoh5GZ0ifKmQGQnJyG/FL3bv6d2iodZ1YVxBZl3LFswiUdBDSK6ek9Kt8emt5/LJbIAPVs2hdCE8/gLyvVXBp6f32LjoQgYr3GOA
    user: AgB6r5IisLnweHhHeEgIF605G8zPgR27Ij5mYQPcBYlZE4rdWSp266kFgK8PTFTjkQajAn1pH2EjPNcx8L6VAQT6iHH8fvT169OAx9oF4MKlXaKKYt7haecAoCSjsMKedgfQQ6oRDiy1k0fkqiXcv7Xi0oc0yUA2fsnZhOTGDazIqR8Cey3F6v6hTT1kGewR2t7s6c/n37Bxd5buYaDMw0deBhZ+arZNLDyY+mzkVCzTSqYpY3dJZmLxXoOjGkndLpfsLInWtU+v/Y52sw4Pq5kC/YQ6UCrg2SamUlvvK/lvkYZDe994ijZCgxd07S9Ob/6jZGjVoBiQyogPfUAW2EGvGb0oj1RhmDCQ/26M64v6tq18n796vy4ahXlAK6B9wtPt4xp74T3eqoHhA64mTkjdCxND08DFpF1zdVOy8rmeV3ICwQMkEws3qnyyz68jRaLWiVSmdRas8TX+yVFv1O5dCDYfM05Qi2jN6N02icYwXbVGUSo7YHFwOrtYc3qSA1DqGVvD03gLIJ013zQ3X/2paFHWxLpMCVWl+IJoMcEBg6Ugo1xPCTwWFBakzGVGopRb8t9HTrryX4GW9C/o95P3zCxyw9zkoyGE3tWOti/gG7N7Q7wQuUHNnNE9c1Rc/BU7wEArGcXrO474kj5sMIYOIbk3gqZZsvmjs4YtTe2jcM0YhlbSO8Hi3SnLhNnKidFTQalaV/MehXF5Z6CJXFPl
  template:
    metadata:
      creationTimestamp: null
      name: jenkins-operator-credentials-jenkins
      namespace: platform
