---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jenkins-operator-credentials-jenkins
  namespace: platform
spec:
  encryptedData:
    token: AgCzyKj6K7tahoOvYmISqohtaYDxC0vTlAirKM5aXtIszisspM4SKYyTjURqGjHp+L3vqEYJvLSxhCEXw9biKxSZaZ6i5gUixam6w8KW3PXlfZcCvJJJvF+2Kw5bNOI5eljvuZG9mgtppJqG3j80uBtzT9ujSyf/hm9FmYhYKCWuRNU2AjQ3E+U7MjQOZkKGVqbbrCgqyP1VBlxsiWmSJ+wLCmK4oxRbl3lAdaibcG2sEMIsoLKaOi1LNu/aNknu5zdmYKh2p6PdfwyH6xjG2OFOJExStmjYN0cOANHTcECSi2ZpOGIiM4qeeCKQHDQBSXXwIGngu8TxpvzCqPg7FBMC5sWbSyU+h6bycb1lQV/cOewmyIagOE53a0Ld89TpNg+off5Kj8lG6GFF7aPkWO2hPz52MXJtUT5PS/uhP+rZanWiZ/N2IOnGlJx0p7lUMMzJ/Y4r8rp/pEl9Rp1s3a8uSmoheTu1Wfubffl6PKeZFbKnd9KPPBLivLqyFEVXAoAamrB4sDdrGhP8lDdSODveosjNiCyBLB372FB1HrfFPUc7sm6I6+vDCmhzOQW3Ru0EnkFJcUJjTvLMlionQk/MmJ0B/5VYhJQUYXJFCn48+adL83f2hXNv3IjJIxHYQXTBGYxUSP6DSQdmu8vT5u2Fct9lAOKSeSbDgJ5EEJNJ16afMt4jsWk0qlvuVtfW+o/N71ihd64hHbKsaWwrx/yK4+gzwAyg+IA1tGQ9vG2FzXKR
    user: AgA1sLOyLyXwIKXbtWanZ2FnNJpdpHHll9Zrzvio/9kktdoocchNlV5x812Ln+0JfDJJpZimzJ9eRfyF3QhMqL/Sjio65a2YIm2gkMNe4bl8bPq6N/3/TEHb5VHV6QDxSIy5HkV5iKE2Z0i4r6pUG2MQXkLA3uKF1MLLTzcbI0/N5F8ghsjDZ+90gsquIYYyvzhM7Jad8G5KmI485GD6dYGhvSrSP25xjA7aCbuB7rfQ06Y2n3q9iYERgoFK314isvEhU1hFj01wVZxJVMWUKkCPaV444imo+Y/FJ0XUL9XsuOG3fHiLNOpEOQd9q98/da2d7S5Ft3Lok3PJCcMEeYq6+eMET9h6ON19ccQLWfHPD6bKuTe/p/w+KI5/QVJNwM1+K5lZtrIX7c7TlY9LUgzhGMcZxtQ77sE3DNbcsfA3u9BwFggyQ33sGXTvnzBLfwoXztD7/yN4vhSRiG8mBHI/6GkRb4BdyrIYYe9t9N4qvX7H6cl8NnaFT1j+E3Quq67inY6zFVJv0hNkEDpbnb6sWAT85WgpeTc0Lp1RNpAEkJTGojz4Jf3s9aYVcgAfALU+Cy9KejQTwrWekHIPBDNA1ZdpZMWw3WKM4eFNc/PLvDbasiiXjvfGBjjGAKDF25QZj+CxTz1NkgQO/sgaJHKKQem+K6bw35PxGpX7b3xVAVLUDTo2rjQ9Fz+gbzMwYABeSTaDJvE8ZeIFBWju1wY+
  template:
    metadata:
      name: jenkins-operator-credentials-jenkins
      namespace: platform
